#!/bin/bash

xargs -L1 ./tcas < v1/finputs.txt  > v1/golden-outputs.txt
xargs -L1 ./tcas < v2/finputs.txt  > v2/golden-outputs.txt
xargs -L1 ./tcas < v3/finputs.txt  > v3/golden-outputs.txt
xargs -L1 ./tcas < v4/finputs.txt  > v4/golden-outputs.txt
xargs -L1 ./tcas < v5/finputs.txt  > v5/golden-outputs.txt
xargs -L1 ./tcas < v6/finputs.txt  > v6/golden-outputs.txt
xargs -L1 ./tcas < v7/finputs.txt  > v7/golden-outputs.txt
xargs -L1 ./tcas < v8/finputs.txt  > v8/golden-outputs.txt
xargs -L1 ./tcas < v9/finputs.txt  > v9/golden-outputs.txt
xargs -L1 ./tcas < v10/finputs.txt  > v10/golden-outputs.txt
xargs -L1 ./tcas < v11/finputs.txt  > v11/golden-outputs.txt
xargs -L1 ./tcas < v12/finputs.txt  > v12/golden-outputs.txt
xargs -L1 ./tcas < v13/finputs.txt  > v13/golden-outputs.txt
xargs -L1 ./tcas < v14/finputs.txt  > v14/golden-outputs.txt
xargs -L1 ./tcas < v15/finputs.txt  > v15/golden-outputs.txt
xargs -L1 ./tcas < v16/finputs.txt  > v16/golden-outputs.txt
xargs -L1 ./tcas < v17/finputs.txt  > v17/golden-outputs.txt
xargs -L1 ./tcas < v18/finputs.txt  > v18/golden-outputs.txt
xargs -L1 ./tcas < v19/finputs.txt  > v19/golden-outputs.txt
xargs -L1 ./tcas < v20/finputs.txt  > v20/golden-outputs.txt
xargs -L1 ./tcas < v21/finputs.txt  > v21/golden-outputs.txt
xargs -L1 ./tcas < v22/finputs.txt  > v22/golden-outputs.txt
xargs -L1 ./tcas < v23/finputs.txt  > v23/golden-outputs.txt
xargs -L1 ./tcas < v24/finputs.txt  > v24/golden-outputs.txt
xargs -L1 ./tcas < v25/finputs.txt  > v25/golden-outputs.txt
xargs -L1 ./tcas < v26/finputs.txt  > v26/golden-outputs.txt
xargs -L1 ./tcas < v27/finputs.txt  > v27/golden-outputs.txt
xargs -L1 ./tcas < v28/finputs.txt  > v28/golden-outputs.txt
xargs -L1 ./tcas < v29/finputs.txt  > v29/golden-outputs.txt
xargs -L1 ./tcas < v30/finputs.txt  > v30/golden-outputs.txt
xargs -L1 ./tcas < v31/finputs.txt  > v31/golden-outputs.txt
xargs -L1 ./tcas < v32/finputs.txt  > v32/golden-outputs.txt
xargs -L1 ./tcas < v33/finputs.txt  > v33/golden-outputs.txt
xargs -L1 ./tcas < v34/finputs.txt  > v34/golden-outputs.txt
xargs -L1 ./tcas < v35/finputs.txt  > v35/golden-outputs.txt
xargs -L1 ./tcas < v36/finputs.txt  > v36/golden-outputs.txt
xargs -L1 ./tcas < v37/finputs.txt  > v37/golden-outputs.txt
xargs -L1 ./tcas < v38/finputs.txt  > v38/golden-outputs.txt
xargs -L1 ./tcas < v39/finputs.txt  > v39/golden-outputs.txt
xargs -L1 ./tcas < v40/finputs.txt  > v40/golden-outputs.txt
xargs -L1 ./tcas < v41/finputs.txt  > v41/golden-outputs.txt