#!/bin/bash

echo "Running SNIPER..."


# version, bug lines
./time-tcas 1 75
./time-tcas 2 63
./time-tcas 3 120
./time-tcas 4 79
./time-tcas 5 118
./time-tcas 6 104
./time-tcas 7 51
./time-tcas 8 53
./time-tcas 9 89
./time-tcas 10 105 111
./time-tcas 11 106 113
./time-tcas 12 118
./time-tcas 13 118   #define at 10
./time-tcas 14 118   #define at 11
./time-tcas 15 79 93 118 #79 and 93define at 12
./time-tcas 16 50
./time-tcas 17 51
./time-tcas 18 52
./time-tcas 19 53
./time-tcas 20 72
./time-tcas 21 72
./time-tcas 22 72
./time-tcas 23 90
./time-tcas 24 90
./time-tcas 25 97
./time-tcas 26 118
./time-tcas 27 118
./time-tcas 28 63
./time-tcas 29 63
./time-tcas 30 63
./time-tcas 31 81 128
./time-tcas 32 99 129
./time-tcas 33 50 51 52 53 
./time-tcas 34 124
./time-tcas 35 63
./time-tcas 36 136  #define at 46
./time-tcas 37 58
./time-tcas 38 58   #define at 27
./time-tcas 39 97
./time-tcas 40 75 126
./time-tcas 41 79
