#!/bin/bash


echo "Running SNIPER..."

# version, bug lines
./tcas-nopp 1 75
./tcas-nopp 2 63
./tcas-nopp 3 120
./tcas-nopp 4 79
./tcas-nopp 5 118
./tcas-nopp 6 104
./tcas-nopp 7 51
./tcas-nopp 8 53
./tcas-nopp 9 89
./tcas-nopp 10 105 111
./tcas-nopp 11 106 113
./tcas-nopp 12 118
./tcas-nopp 13 118   #define at 10
./tcas-nopp 14 118   #define at 11
./tcas-nopp 15 79 93 118 #79 and 93define at 12
./tcas-nopp 16 50
./tcas-nopp 17 51
./tcas-nopp 18 52
./tcas-nopp 19 53
./tcas-nopp 20 72
./tcas-nopp 21 72
./tcas-nopp 22 72
./tcas-nopp 23 90
./tcas-nopp 24 90
./tcas-nopp 25 97
./tcas-nopp 26 118
./tcas-nopp 27 118
./tcas-nopp 28 63
./tcas-nopp 29 63
./tcas-nopp 30 63
./tcas-nopp 31 81 128
./tcas-nopp 32 99 129
./tcas-nopp 33 50 51 52 53 
./tcas-nopp 34 124
./tcas-nopp 35 63
./tcas-nopp 36 136  #define at 46
./tcas-nopp 37 58
./tcas-nopp 38 58   #define at 27
./tcas-nopp 39 97
./tcas-nopp 40 75 126
./tcas-nopp 41 79





