#!/bin/bash


echo "Running SNIPER..."

./sniper foo ./examples/concolic_tcas/v1/tcas.c > ./examples/concolic_tcas/v1/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v2/tcas.c > ./examples/concolic_tcas/v2/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v3/tcas.c > ./examples/concolic_tcas/v3/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v4/tcas.c > ./examples/concolic_tcas/v4/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v5/tcas.c > ./examples/concolic_tcas/v5/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v6/tcas.c > ./examples/concolic_tcas/v6/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v7/tcas.c > ./examples/concolic_tcas/v7/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v8/tcas.c > ./examples/concolic_tcas/v8/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v9/tcas.c > ./examples/concolic_tcas/v9/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v10/tcas.c > ./examples/concolic_tcas/v10/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v11/tcas.c > ./examples/concolic_tcas/v11/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v12/tcas.c > ./examples/concolic_tcas/v12/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v13/tcas.c > ./examples/concolic_tcas/v13/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v14/tcas.c > ./examples/concolic_tcas/v14/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v15/tcas.c > ./examples/concolic_tcas/v15/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v16/tcas.c > ./examples/concolic_tcas/v16/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v17/tcas.c > ./examples/concolic_tcas/v17/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v18/tcas.c > ./examples/concolic_tcas/v18/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v19/tcas.c > ./examples/concolic_tcas/v19/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v20/tcas.c > ./examples/concolic_tcas/v20/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v21/tcas.c > ./examples/concolic_tcas/v21/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v22/tcas.c > ./examples/concolic_tcas/v22/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v23/tcas.c > ./examples/concolic_tcas/v23/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v24/tcas.c > ./examples/concolic_tcas/v24/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v25/tcas.c > ./examples/concolic_tcas/v25/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v26/tcas.c > ./examples/concolic_tcas/v26/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v27/tcas.c > ./examples/concolic_tcas/v27/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v28/tcas.c > ./examples/concolic_tcas/v28/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v29/tcas.c > ./examples/concolic_tcas/v29/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v30/tcas.c > ./examples/concolic_tcas/v30/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v31/tcas.c > ./examples/concolic_tcas/v31/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v32/tcas.c > ./examples/concolic_tcas/v32/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v33/tcas.c > ./examples/concolic_tcas/v33/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v34/tcas.c > ./examples/concolic_tcas/v34/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v35/tcas.c > ./examples/concolic_tcas/v35/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v36/tcas.c > ./examples/concolic_tcas/v36/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v37/tcas.c > ./examples/concolic_tcas/v37/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v38/tcas.c > ./examples/concolic_tcas/v38/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v39/tcas.c > ./examples/concolic_tcas/v39/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v40/tcas.c > ./examples/concolic_tcas/v40/inputs_cute.txt
./sniper foo ./examples/concolic_tcas/v41/tcas.c > ./examples/concolic_tcas/v41/inputs_cute.txt

cat ./examples/concolic_tcas/v1/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v1/golden_cute.txt
cat ./examples/concolic_tcas/v2/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v2/golden_cute.txt
cat ./examples/concolic_tcas/v3/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v3/golden_cute.txt
cat ./examples/concolic_tcas/v4/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v4/golden_cute.txt
cat ./examples/concolic_tcas/v5/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v5/golden_cute.txt
cat ./examples/concolic_tcas/v6/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v6/golden_cute.txt
cat ./examples/concolic_tcas/v7/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v7/golden_cute.txt
cat ./examples/concolic_tcas/v8/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v8/golden_cute.txt
cat ./examples/concolic_tcas/v9/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v9/golden_cute.txt
cat ./examples/concolic_tcas/v10/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v10/golden_cute.txt
cat ./examples/concolic_tcas/v11/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v11/golden_cute.txt
cat ./examples/concolic_tcas/v12/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v12/golden_cute.txt
cat ./examples/concolic_tcas/v13/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v13/golden_cute.txt
cat ./examples/concolic_tcas/v14/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v14/golden_cute.txt
cat ./examples/concolic_tcas/v15/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v15/golden_cute.txt
cat ./examples/concolic_tcas/v16/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v16/golden_cute.txt
cat ./examples/concolic_tcas/v17/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v17/golden_cute.txt
cat ./examples/concolic_tcas/v18/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v18/golden_cute.txt
cat ./examples/concolic_tcas/v19/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v19/golden_cute.txt
cat ./examples/concolic_tcas/v20/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v20/golden_cute.txt
cat ./examples/concolic_tcas/v21/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v21/golden_cute.txt
cat ./examples/concolic_tcas/v22/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v22/golden_cute.txt
cat ./examples/concolic_tcas/v23/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v23/golden_cute.txt
cat ./examples/concolic_tcas/v24/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v24/golden_cute.txt
cat ./examples/concolic_tcas/v25/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v25/golden_cute.txt
cat ./examples/concolic_tcas/v26/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v26/golden_cute.txt
cat ./examples/concolic_tcas/v27/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v27/golden_cute.txt
cat ./examples/concolic_tcas/v28/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v28/golden_cute.txt
cat ./examples/concolic_tcas/v29/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v29/golden_cute.txt
cat ./examples/concolic_tcas/v30/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v30/golden_cute.txt
cat ./examples/concolic_tcas/v31/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v31/golden_cute.txt
cat ./examples/concolic_tcas/v32/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v32/golden_cute.txt
cat ./examples/concolic_tcas/v33/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v33/golden_cute.txt
cat ./examples/concolic_tcas/v34/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v34/golden_cute.txt
cat ./examples/concolic_tcas/v35/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v35/golden_cute.txt
cat ./examples/concolic_tcas/v36/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v36/golden_cute.txt
cat ./examples/concolic_tcas/v37/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v37/golden_cute.txt
cat ./examples/concolic_tcas/v38/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v38/golden_cute.txt
cat ./examples/concolic_tcas/v39/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v39/golden_cute.txt
cat ./examples/concolic_tcas/v40/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v40/golden_cute.txt
cat ./examples/concolic_tcas/v41/inputs_cute.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v41/golden_cute.txt






