#!/bin/bash


echo "Running..."

./run foo ./examples/concolic_tcas/v1/tcas_noarray.c > ./examples/concolic_tcas/v1/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v2/tcas_noarray.c > ./examples/concolic_tcas/v2/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v3/tcas_noarray.c > ./examples/concolic_tcas/v3/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v4/tcas_noarray.c > ./examples/concolic_tcas/v4/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v5/tcas_noarray.c > ./examples/concolic_tcas/v5/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v6/tcas_noarray.c > ./examples/concolic_tcas/v6/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v7/tcas_noarray.c > ./examples/concolic_tcas/v7/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v8/tcas_noarray.c > ./examples/concolic_tcas/v8/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v9/tcas_noarray.c > ./examples/concolic_tcas/v9/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v10/tcas_noarray.c > ./examples/concolic_tcas/v10/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v11/tcas_noarray.c > ./examples/concolic_tcas/v11/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v12/tcas_noarray.c > ./examples/concolic_tcas/v12/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v13/tcas_noarray.c > ./examples/concolic_tcas/v13/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v14/tcas_noarray.c > ./examples/concolic_tcas/v14/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v15/tcas_noarray.c > ./examples/concolic_tcas/v15/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v16/tcas_noarray.c > ./examples/concolic_tcas/v16/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v17/tcas_noarray.c > ./examples/concolic_tcas/v17/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v18/tcas_noarray.c > ./examples/concolic_tcas/v18/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v19/tcas_noarray.c > ./examples/concolic_tcas/v19/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v20/tcas_noarray.c > ./examples/concolic_tcas/v20/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v21/tcas_noarray.c > ./examples/concolic_tcas/v21/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v22/tcas_noarray.c > ./examples/concolic_tcas/v22/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v23/tcas_noarray.c > ./examples/concolic_tcas/v23/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v24/tcas_noarray.c > ./examples/concolic_tcas/v24/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v25/tcas_noarray.c > ./examples/concolic_tcas/v25/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v26/tcas_noarray.c > ./examples/concolic_tcas/v26/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v27/tcas_noarray.c > ./examples/concolic_tcas/v27/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v28/tcas_noarray.c > ./examples/concolic_tcas/v28/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v29/tcas_noarray.c > ./examples/concolic_tcas/v29/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v30/tcas_noarray.c > ./examples/concolic_tcas/v30/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v31/tcas_noarray.c > ./examples/concolic_tcas/v31/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v32/tcas_noarray.c > ./examples/concolic_tcas/v32/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v33/tcas_noarray.c > ./examples/concolic_tcas/v33/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v34/tcas_noarray.c > ./examples/concolic_tcas/v34/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v35/tcas_noarray.c > ./examples/concolic_tcas/v35/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v36/tcas_noarray.c > ./examples/concolic_tcas/v36/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v37/tcas_noarray.c > ./examples/concolic_tcas/v37/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v38/tcas_noarray.c > ./examples/concolic_tcas/v38/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v39/tcas_noarray.c > ./examples/concolic_tcas/v39/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v40/tcas_noarray.c > ./examples/concolic_tcas/v40/inputs_noarray.txt
./run foo ./examples/concolic_tcas/v41/tcas_noarray.c > ./examples/concolic_tcas/v41/inputs_noarray.txt

cat ./examples/concolic_tcas/v1/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v1/golden_noarray.txt
cat ./examples/concolic_tcas/v2/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v2/golden_noarray.txt
cat ./examples/concolic_tcas/v3/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v3/golden_noarray.txt
cat ./examples/concolic_tcas/v4/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v4/golden_noarray.txt
cat ./examples/concolic_tcas/v5/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v5/golden_noarray.txt
cat ./examples/concolic_tcas/v6/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v6/golden_noarray.txt
cat ./examples/concolic_tcas/v7/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v7/golden_noarray.txt
cat ./examples/concolic_tcas/v8/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v8/golden_noarray.txt
cat ./examples/concolic_tcas/v9/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v9/golden_noarray.txt
cat ./examples/concolic_tcas/v10/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v10/golden_noarray.txt
cat ./examples/concolic_tcas/v11/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v11/golden_noarray.txt
cat ./examples/concolic_tcas/v12/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v12/golden_noarray.txt
cat ./examples/concolic_tcas/v13/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v13/golden_noarray.txt
cat ./examples/concolic_tcas/v14/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v14/golden_noarray.txt
cat ./examples/concolic_tcas/v15/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v15/golden_noarray.txt
cat ./examples/concolic_tcas/v16/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v16/golden_noarray.txt
cat ./examples/concolic_tcas/v17/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v17/golden_noarray.txt
cat ./examples/concolic_tcas/v18/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v18/golden_noarray.txt
cat ./examples/concolic_tcas/v19/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v19/golden_noarray.txt
cat ./examples/concolic_tcas/v20/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v20/golden_noarray.txt
cat ./examples/concolic_tcas/v21/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v21/golden_noarray.txt
cat ./examples/concolic_tcas/v22/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v22/golden_noarray.txt
cat ./examples/concolic_tcas/v23/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v23/golden_noarray.txt
cat ./examples/concolic_tcas/v24/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v24/golden_noarray.txt
cat ./examples/concolic_tcas/v25/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v25/golden_noarray.txt
cat ./examples/concolic_tcas/v26/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v26/golden_noarray.txt
cat ./examples/concolic_tcas/v27/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v27/golden_noarray.txt
cat ./examples/concolic_tcas/v28/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v28/golden_noarray.txt
cat ./examples/concolic_tcas/v29/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v29/golden_noarray.txt
cat ./examples/concolic_tcas/v30/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v30/golden_noarray.txt
cat ./examples/concolic_tcas/v31/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v31/golden_noarray.txt
cat ./examples/concolic_tcas/v32/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v32/golden_noarray.txt
#cat ./examples/concolic_tcas/v33/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v33/golden_noarray.txt
cat ./examples/concolic_tcas/v34/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v34/golden_noarray.txt
cat ./examples/concolic_tcas/v35/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v35/golden_noarray.txt
cat ./examples/concolic_tcas/v36/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v36/golden_noarray.txt
cat ./examples/concolic_tcas/v37/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v37/golden_noarray.txt
cat ./examples/concolic_tcas/v38/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v38/golden_noarray.txt
cat ./examples/concolic_tcas/v39/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v39/golden_noarray.txt
cat ./examples/concolic_tcas/v40/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v40/golden_noarray.txt
cat ./examples/concolic_tcas/v41/inputs_noarray.txt | xargs -L 1 ./examples/concolic_tcas/tcas > ./examples/concolic_tcas/v41/golden_noarray.txt






