#!/bin/bash


if [ $# -lt 2 ]
then 
  echo "error (x_X)"
  exit 0
fi

path=./examples/tcas/v$1/tcas.c
llvm-gcc -emit-llvm -O0 -g $path -c -o $path.bc >error 2>&1

echo " "
echo "TCAS n°$1"
if [ $# -lt 3 ]
then 
  ./tool -print-dura -unroll-count 0 -function main -cfile $path $path.bc -tl1 $2 
elif [ $# -lt 4 ]
then 
  ./tool -print-dura -unroll-count 0 -function main -cfile $path $path.bc -tl1 $2 -tl2 $3 
elif [ $# -lt 5 ]
then 
  ./tool -print-dura -unroll-count 0 -function main -cfile $path $path.bc -tl1 $2 -tl2 $3 -tl3 $4
fi

